default_job = "watch"
env.CARGO_TERM_COLOR = "always"

[jobs.check]
command = ["cargo", "check"]
need_stdout = false

[jobs.test]
command = ["cargo", "test"]
need_stdout = true

[jobs.run]
command = ["cargo", "run"]
need_stdout = true
allow_warnings = true
background = true

[jobs.watch]
command = ["cargo", "run"]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"


[keybindings]
