[package]
name = "creek"
version = "0.1.0"
edition = "2021"

[lib]
name = "creek"
path = "src/lib.rs"

[[bin]]
name = "creek"
path = "src/main.rs"

[dependencies]
actix-casbin = { version = "1.1.0", default-features = false, features = [
  "runtime-tokio",
  "tokio",
] }
actix-casbin-auth = { version = "1.1.0", default-features = false, features = [
  "runtime-tokio",
  "tokio",
] }
actix-web = "4.9.0"
argon2 = { version = "0.5.3", features = ["simple", "std", "zeroize"] }
base64 = "0.22.1"
envy = "0.4.2"
eyre = "0.6.12"
pom = "3.4.0"
rand = "0.8.5"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
snafu = "0.8.5"
sqlx = { version = "0.8.2", features = [
  "runtime-tokio",
  "sqlite",
  "tls-native-tls",
] }
tokio = { version = "1.41.1", features = ["full"] }
tokio-stream = { version = "0.1.16", features = ["full"] }
tracing = { version = "0.1.40", features = ["async-await"] }
tracing-actix-web = "0.7.14"
tracing-subscriber = { version = "0.3.18", features = ["tracing", "serde"] }

[dev-dependencies]
tempfile = "3.14.0"
