[package]
name = "creek"
version = "0.1.0"
edition = "2021"

[lib]
name = "creek"
path = "src/lib.rs"

[[bin]]
name = "creek"
path = "src/main.rs"

[dependencies]
actix-web = "4.9.0"
envy = "0.4.2"
eyre = "0.6.12"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
snafu = "0.8.5"
sqlx = { version = "0.8.2", features = [
  "runtime-tokio",
  "sqlite",
  "tls-native-tls",
] }
tokio = { version = "1.41.1", features = ["full"] }
tokio-stream = { version = "0.1.16", features = ["full"] }

[dev-dependencies]
tempfile = "3.14.0"
